language: python
install:
  - pip install tox
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database denorm_test;' -U postgres; fi;"

  - sh -c "if [ '$DB' = 'postgis' ]; then psql -c 'create database denorm_test;' -U postgres; fi;"
  - sh -c "if [ '$DB' = 'postgis' ]; then psql -c 'create extension postgis;' -U postgres; fi;"

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database denorm_test;'; fi"
script:
  - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO}-${DB}

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  - DJANGO=django15 DB=sqlite
  - DJANGO=django16 DB=sqlite
  - DJANGO=django15 DB=sqlite
  - DJANGO=django16 DB=sqlite
  - DJANGO=django17 DB=sqlite
  - DJANGO=django18 DB=sqlite
  - DJANGO=django19 DB=sqlite
  - DJANGO=djangomaster DB=sqlite

  - DJANGO=django15 DB=mysql
  - DJANGO=django16 DB=mysql
  - DJANGO=django15 DB=mysql
  - DJANGO=django16 DB=mysql
  - DJANGO=django17 DB=mysql
  - DJANGO=django18 DB=mysql
  - DJANGO=django19 DB=mysql
  - DJANGO=djangomaster DB=mysql

  - DJANGO=django15 DB=postgres
  - DJANGO=django16 DB=postgres
  - DJANGO=django15 DB=postgres
  - DJANGO=django16 DB=postgres
  - DJANGO=django17 DB=postgres
  - DJANGO=django18 DB=postgres
  - DJANGO=django19 DB=postgres
  - DJANGO=djangomaster DB=postgres

  - DJANGO=django18 DB=postgis
  - DJANGO=django19 DB=postgis
  - DJANGO=djangomaster DB=postgis

matrix:
  fast_finish: true
  exclude:
    - python: "2.6"
      env: DJANGO=django17 DB=sqlite
    - python: "2.6"
      env: DJANGO=django18 DB=sqlite
    - python: "2.6"
      env: DJANGO=django19 DB=sqlite
    - python: "2.6"
      env: DJANGO=djangomaster DB=sqlite
    - python: "2.6"
      env: DJANGO=django17 DB=mysql
    - python: "2.6"
      env: DJANGO=django18 DB=mysql
    - python: "2.6"
      env: DJANGO=django19 DB=mysql
    - python: "2.6"
      env: DJANGO=djangomaster DB=mysql
    - python: "2.6"
      env: DJANGO=django17 DB=postgres
    - python: "2.6"
      env: DJANGO=django18 DB=postgres
    - python: "2.6"
      env: DJANGO=django19 DB=postgres
    - python: "2.6"
      env: DJANGO=djangomaster DB=postgres
    - python: "2.6"
      env: DJANGO=django17 DB=postgis
    - python: "2.6"
      env: DJANGO=django18 DB=postgis
    - python: "2.6"
      env: DJANGO=django19 DB=postgis
    - python: "2.6"
      env: DJANGO=djangomaster DB=postgis
  allow_failures:
    - env: DJANGO=djangomaster DB=sqlite
    - env: DJANGO=djangomaster DB=mysql
    - env: DJANGO=djangomaster DB=postgres
    - env: DJANGO=djangomaster DB=postgis
